spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studio_medico_progetto
    username: root
    password: qwerty12345678910#
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls[0]:
      name: 'name'
      url: '/v3/api-docs'

server:
  port: 8080
