-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 16:49:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`study` (
  `idstudy` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idstudy`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `iddoctor` INT NOT NULL AUTO_INCREMENT,
  `study_idstudy` INT NOT NULL,
  PRIMARY KEY (`iddoctor`),
  INDEX `fk_doctor_study_idx` (`study_idstudy` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_study`
    FOREIGN KEY (`study_idstudy`)
    REFERENCES `mydb`.`study` (`idstudy`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secretary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secretary` (
  `idsecretary` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idsecretary`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `idpatient` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idpatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `idbooking` INT NOT NULL AUTO_INCREMENT,
  `patient_idpatient` INT NOT NULL,
  `doctor_iddoctor` INT NOT NULL,
  `secretary_idsecretary` INT NOT NULL,
  PRIMARY KEY (`idbooking`),
  INDEX `fk_booking_patient1_idx` (`patient_idpatient` ASC) VISIBLE,
  INDEX `fk_booking_doctor1_idx` (`doctor_iddoctor` ASC) VISIBLE,
  INDEX `fk_booking_secretary1_idx` (`secretary_idsecretary` ASC) VISIBLE,
  CONSTRAINT `fk_booking_patient1`
    FOREIGN KEY (`patient_idpatient`)
    REFERENCES `mydb`.`patient` (`idpatient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_doctor1`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `mydb`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_secretary1`
    FOREIGN KEY (`secretary_idsecretary`)
    REFERENCES `mydb`.`secretary` (`idsecretary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;