-- MySQL Script generated by MySQL Workbench
-- Mon Feb 27 17:22:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema studio_medico_progetto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema studio_medico_progetto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studio_medico_progetto` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema studio_medico_progetto
-- -----------------------------------------------------
USE `studio_medico_progetto` ;

-- -----------------------------------------------------
-- Table `studio_medico_progetto`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio_medico_progetto`.`doctor` (
  `iddoctor` INT NOT NULL AUTO_INCREMENT,
  `doctorName` VARCHAR(45) NULL,
  `doctorSurname` VARCHAR(45) NULL,
  `doctorSpecializzation` VARCHAR(45) NULL,
  `doctorEmail` VARCHAR(45) NULL,
  `officeContact` VARCHAR(45) NULL,
  `placeOfWork` VARCHAR(45) NULL,
  `workingDays` INT NULL,
  PRIMARY KEY (`iddoctor`),
  UNIQUE INDEX `doctorEmail_UNIQUE` (`doctorEmail` ASC) VISIBLE,
  UNIQUE INDEX `officeContact_UNIQUE` (`officeContact` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio_medico_progetto`.`secretary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studio_medico_progetto`.`secretary` (
  `idsecretary` INT NOT NULL AUTO_INCREMENT,
  `doctor_iddoctor` INT NOT NULL,
  `secretaryName` VARCHAR(45) NULL,
  `secretarySurname` VARCHAR(45) NULL,
  `secretaryEmail` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `workingDays` INT NULL,
  PRIMARY KEY (`idsecretary`),
  INDEX `fk_secretary_doctor1_idx` (`doctor_iddoctor` ASC) VISIBLE,
  UNIQUE INDEX `secretaryEmail_UNIQUE` (`secretaryEmail` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  CONSTRAINT `fk_secretary_doctor1`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `studio_medico_progetto`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio_medico_progetto`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `idbooking` INT NOT NULL AUTO_INCREMENT,
  `doctor_iddoctor` INT NOT NULL,
  `bookingDate` DATE NULL,
  `status` TINYINT NULL,
  `patient_healthInsuranceCard` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbooking`),
  INDEX `fk_booking_doctor1_idx` (`doctor_iddoctor` ASC) VISIBLE,
  INDEX `fk_booking_patient1_idx` (`patient_healthInsuranceCard` ASC) VISIBLE,
  CONSTRAINT `fk_booking_doctor1`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `mydb`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_booking_patient1`
    FOREIGN KEY (`patient_healthInsuranceCard`)
    REFERENCES `mydb`.`patient` (`healthInsuranceCard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studio_medico_progetto`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `healthInsuranceCard` VARCHAR(45) NOT NULL,
  `doctor_iddoctor` INT NOT NULL,
  `patientName` VARCHAR(45) NULL,
  `patientSurname` VARCHAR(45) NULL,
  `patientEmail` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`healthInsuranceCard`),
  INDEX `fk_patient_doctor1_idx` (`doctor_iddoctor` ASC) VISIBLE,
  UNIQUE INDEX `patientEmail_UNIQUE` (`patientEmail` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  CONSTRAINT `fk_patient_doctor1`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `mydb`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
